# Setup
title:        GitHub do Vinicius
tagline:      Alguns projetos
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Marcos Vinicius
  url:        https://acogero.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown